Added unit tests for hash algorithms.

diff --git a/tests/Makefile.in b/tests/Makefile.in
--- a/tests/Makefile.in
+++ b/tests/Makefile.in
@@ -11,9 +11,9 @@
 # PARTICULAR PURPOSE.
 
 #
-# Makefile.am's purpose is to build the beetest test program.
+# Makefile.am's purpose is to build the beetest_ test_ program.
 #
-# Copyright (c) 2001 Virtual Unlimited B.V.
+# Copyright (c) 2001, 2002 Virtual Unlimited B.V.
 #
 # Author: Bob Deblier <bob@virtualunlimited.com>
 #
@@ -107,6 +107,18 @@ AUTOMAKE_OPTIONS = gnu no-dependencies
 INCLUDES = -I$(top_srcdir)
 LDADD = $(top_builddir)/libbeecrypt.la
 
+TESTS = testmd5 testsha1 testsha256 testhmacmd5 
+
+check_PROGRAMS = testmd5 testsha1 testsha256 testhmacmd5 
+
+testmd5_SOURCES = testmd5.c
+
+testsha1_SOURCES = testsha1.c
+
+testsha256_SOURCES = testsha256.c
+
+testhmacmd5_SOURCES = testhmacmd5.c
+
 EXTRA_PROGRAMS = beetest
 
 beetest_SOURCES = beetest.c
@@ -122,6 +134,22 @@ beetest_OBJECTS =  beetest.o
 beetest_LDADD = $(LDADD)
 beetest_DEPENDENCIES =  $(top_builddir)/libbeecrypt.la
 beetest_LDFLAGS = 
+testmd5_OBJECTS =  testmd5.o
+testmd5_LDADD = $(LDADD)
+testmd5_DEPENDENCIES =  $(top_builddir)/libbeecrypt.la
+testmd5_LDFLAGS = 
+testsha1_OBJECTS =  testsha1.o
+testsha1_LDADD = $(LDADD)
+testsha1_DEPENDENCIES =  $(top_builddir)/libbeecrypt.la
+testsha1_LDFLAGS = 
+testsha256_OBJECTS =  testsha256.o
+testsha256_LDADD = $(LDADD)
+testsha256_DEPENDENCIES =  $(top_builddir)/libbeecrypt.la
+testsha256_LDFLAGS = 
+testhmacmd5_OBJECTS =  testhmacmd5.o
+testhmacmd5_LDADD = $(LDADD)
+testhmacmd5_DEPENDENCIES =  $(top_builddir)/libbeecrypt.la
+testhmacmd5_LDFLAGS = 
 CFLAGS = @CFLAGS@
 COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
 LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
@@ -134,8 +162,8 @@ DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
 
 TAR = tar
 GZIP_ENV = --best
-SOURCES = $(beetest_SOURCES)
-OBJECTS = $(beetest_OBJECTS)
+SOURCES = $(beetest_SOURCES) $(testmd5_SOURCES) $(testsha1_SOURCES) $(testsha256_SOURCES) $(testhmacmd5_SOURCES)
+OBJECTS = $(beetest_OBJECTS) $(testmd5_OBJECTS) $(testsha1_OBJECTS) $(testsha256_OBJECTS) $(testhmacmd5_OBJECTS)
 
 all: all-redirect
 .SUFFIXES:
@@ -147,6 +175,15 @@ Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
 	cd $(top_builddir) \
 	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
 
+
+mostlyclean-checkPROGRAMS:
+
+clean-checkPROGRAMS:
+	-test -z "$(check_PROGRAMS)" || rm -f $(check_PROGRAMS)
+
+distclean-checkPROGRAMS:
+
+maintainer-clean-checkPROGRAMS:
 
 .c.o:
 	$(COMPILE) -c $<
@@ -189,6 +226,22 @@ maintainer-clean-libtool:
 beetest: $(beetest_OBJECTS) $(beetest_DEPENDENCIES)
 	@rm -f beetest
 	$(LINK) $(beetest_LDFLAGS) $(beetest_OBJECTS) $(beetest_LDADD) $(LIBS)
+
+testmd5: $(testmd5_OBJECTS) $(testmd5_DEPENDENCIES)
+	@rm -f testmd5
+	$(LINK) $(testmd5_LDFLAGS) $(testmd5_OBJECTS) $(testmd5_LDADD) $(LIBS)
+
+testsha1: $(testsha1_OBJECTS) $(testsha1_DEPENDENCIES)
+	@rm -f testsha1
+	$(LINK) $(testsha1_LDFLAGS) $(testsha1_OBJECTS) $(testsha1_LDADD) $(LIBS)
+
+testsha256: $(testsha256_OBJECTS) $(testsha256_DEPENDENCIES)
+	@rm -f testsha256
+	$(LINK) $(testsha256_LDFLAGS) $(testsha256_OBJECTS) $(testsha256_LDADD) $(LIBS)
+
+testhmacmd5: $(testhmacmd5_OBJECTS) $(testhmacmd5_DEPENDENCIES)
+	@rm -f testhmacmd5
+	$(LINK) $(testhmacmd5_LDFLAGS) $(testhmacmd5_OBJECTS) $(testhmacmd5_LDADD) $(LIBS)
 
 tags: TAGS
 
@@ -234,11 +287,38 @@ distdir: $(DISTFILES)
 	    || cp -p $$d/$$file $(distdir)/$$file || :; \
 	  fi; \
 	done
+check-TESTS: $(TESTS)
+	@failed=0; all=0; \
+	srcdir=$(srcdir); export srcdir; \
+	for tst in $(TESTS); do \
+	  if test -f $$tst; then dir=.; \
+	  else dir="$(srcdir)"; fi; \
+	  if $(TESTS_ENVIRONMENT) $$dir/$$tst; then \
+	    all=`expr $$all + 1`; \
+	    echo "PASS: $$tst"; \
+	  elif test $$? -ne 77; then \
+	    all=`expr $$all + 1`; \
+	    failed=`expr $$failed + 1`; \
+	    echo "FAIL: $$tst"; \
+	  fi; \
+	done; \
+	if test "$$failed" -eq 0; then \
+	  banner="All $$all tests passed"; \
+	else \
+	  banner="$$failed of $$all tests failed"; \
+	fi; \
+	dashes=`echo "$$banner" | sed s/./=/g`; \
+	echo "$$dashes"; \
+	echo "$$banner"; \
+	echo "$$dashes"; \
+	test "$$failed" -eq 0
 info-am:
 info: info-am
 dvi-am:
 dvi: dvi-am
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
 installcheck-am:
 installcheck: installcheck-am
@@ -269,23 +349,26 @@ distclean-generic:
 	-rm -f config.cache config.log stamp-h stamp-h[0-9]*
 
 maintainer-clean-generic:
-mostlyclean-am:  mostlyclean-compile mostlyclean-libtool \
-		mostlyclean-tags mostlyclean-generic
+mostlyclean-am:  mostlyclean-checkPROGRAMS mostlyclean-compile \
+		mostlyclean-libtool mostlyclean-tags \
+		mostlyclean-generic
 
 mostlyclean: mostlyclean-am
 
-clean-am:  clean-compile clean-libtool clean-tags clean-generic \
-		mostlyclean-am
+clean-am:  clean-checkPROGRAMS clean-compile clean-libtool clean-tags \
+		clean-generic mostlyclean-am
 
 clean: clean-am
 
-distclean-am:  distclean-compile distclean-libtool distclean-tags \
-		distclean-generic clean-am
+distclean-am:  distclean-checkPROGRAMS distclean-compile \
+		distclean-libtool distclean-tags distclean-generic \
+		clean-am
 	-rm -f libtool
 
 distclean: distclean-am
 
-maintainer-clean-am:  maintainer-clean-compile maintainer-clean-libtool \
+maintainer-clean-am:  maintainer-clean-checkPROGRAMS \
+		maintainer-clean-compile maintainer-clean-libtool \
 		maintainer-clean-tags maintainer-clean-generic \
 		distclean-am
 	@echo "This command is intended for maintainers to use;"
@@ -293,10 +376,12 @@ maintainer-clean-am:  maintainer-clean-compile maintainer-clean-libtool \
 
 maintainer-clean: maintainer-clean-am
 
-.PHONY: mostlyclean-compile distclean-compile clean-compile \
-maintainer-clean-compile mostlyclean-libtool distclean-libtool \
-clean-libtool maintainer-clean-libtool tags mostlyclean-tags \
-distclean-tags clean-tags maintainer-clean-tags distdir info-am info \
+.PHONY: mostlyclean-checkPROGRAMS distclean-checkPROGRAMS \
+clean-checkPROGRAMS maintainer-clean-checkPROGRAMS mostlyclean-compile \
+distclean-compile clean-compile maintainer-clean-compile \
+mostlyclean-libtool distclean-libtool clean-libtool \
+maintainer-clean-libtool tags mostlyclean-tags distclean-tags \
+clean-tags maintainer-clean-tags distdir check-TESTS info-am info \
 dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
 install-exec install-data-am install-data install-am install \
 uninstall-am uninstall all-redirect all-am all installdirs \
